### ISSUE TITLE
TypeError: sslChecker is not a function

### ISSUE THREAD

**Issue by RedFlames** [toolisticon/ssl-hostinfo-prometheus-exporter#98]
So I'm getting this warning/error but I might also just be doing something else wrong. 

---

Let me start with what I've done:

1. installed **node** via **nvm**
2. installed **ssl-hostinfo-prometheus-exporter** via **npm i -g ...**
3. Tried **running ssl-hostinfo-prom**

At this point I have a symlink in `/home/prometheus/.nvm/versions/node/v12.18.4/bin` (or wherever $NVM_BIN is currently pointing for my node version)
```
ssl-hostinfo-prom -> ../lib/node_modules/@toolisticon/ssl-hostinfo-prometheus-exporter/app.js
```
...which means when I try to run for example `nvm exec node ssl-hostinfo-prom` (or `$NVM_BIN/ssl-hostinfo-prom`, etc.) apparently it's still somehow bash trying to run the app.js, because I get
```
Running node v14.12.0 (npm v6.14.8)
/home/prometheus/.nvm/versions/node/v14.12.0/bin/ssl-hostinfo-prom: line 1: syntax error near unexpected token `('
/home/prometheus/.nvm/versions/node/v14.12.0/bin/ssl-hostinfo-prom: line 1: `const CronJob = require('cron').CronJob;'
```
or I'm not entirely sure what's happening here. How am I supposed to run it? 

---

4. In any case I managed to run it via `URLS_TO_CHECK=www.google.de LOG_LEVEL=INFO node ${NVM_BIN%/bin}/lib/node_modules/@toolisticon/ssl-hostinfo-prometheus-exporter/app.js` 
this way at least it starts doing something...
```
INFO @ 2020-09-28T14:32:34.758Z : [log4bro] Logger is: in-prod=false, in-docker:false, level=DEBUG, skipDebug=false
INFO @ 2020-09-28T14:32:34.899Z : ssl-hostinfo-prometheus-exporter info
INFO @ 2020-09-28T14:32:34.905Z : Start reading route information.
INFO @ 2020-09-28T14:32:34.905Z : Triggering scan for www.google.de
INFO @ 2020-09-28T14:32:34.905Z : Triggering scan for www.google.de
INFO @ 2020-09-28T14:32:34.910Z : prometheus-exporter listening at 9000
INFO @ 2020-09-28T14:32:35.109Z : Reading scan results for www.google.de
INFO @ 2020-09-28T14:32:35.472Z : Skipping invalid response for mozilla scoring
(node:24996) UnhandledPromiseRejectionWarning: TypeError: sslChecker is not a function
    at receiveScanResult (/home/prometheus/.nvm/versions/node/v12.18.4/lib/node_modules/@toolisticon/ssl-hostinfo-prometheus-exporter/index.js:37:3)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:24996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
is the warning even a problem? Whatever I do I can't seem to find the **security_ssl_...** metrics in prometheus/Grafana...

Oh and when it is running on port 9000 of my server I find:
```
# HELP security_ssl_mozilla_observatory Mozilla Observatory SSL stats
# HELP security_ssl_details Generic SSL Details
# HELP security_ssl_expire_days_remaining Remaining Days before certificate expiry
```
is this what I should expect at this point?

---

I've tried running v1.4.3 and v1.3.0 on node lts/dubnium, lts/* (erbium) and latest (v10.22.1 / v12.18.4 / v14.12.0 respectively).

This is a Debian 9.7 (stretch) server btw. Any help appreciated!

**Comment by hypery2k** [comment]
First of all, thanks for reporting. I think you can give `ssl-hostinfo-prometheus-exporter@1.4.3-build1601310274` a try ;)

**Comment by RedFlames** [comment]
Hey, thanks for the quick response!

I tried your new version, but not much seems to change. I did get a **security_ssl_mozilla_observatory** metric for google just now, but not when I put in the other URLs I actually want to be checking.

I'm still getting the promise warning. I saw node also has a ` --use_strict` flag but apparently that's undocumented and doesn't change much for me either.

If I add the `--unhandled-rejections=strict` flag as node suggests, it (predictably perhaps) terminates from the unhandled promise rejection. 🤔 

---

So what I've found now is this:
https://github.com/dyaa/ssl-checker/issues/44

Which looks like it should've been fixed in ssl-checker@2.0.5 but if I check that out:
```sh
tar -xOf <(curl -o - https://registry.npmjs.org/ssl-checker/-/ssl-checker-2.0.5.tgz | gzip -cd) package/lib/index.d.ts
```
there's no `module.exports = sslChecker;` as there should be at the end...

So I put the workaround mentioned there into your index,js:
```js
//const sslChecker = require('ssl-checker');
const sslChecker = require('ssl-checker').default;
```

and that makes the warnings go away! I'm also seeing the metrics on the exporter now, will check if things are working as intended now. 🤞

**Comment by hypery2k** [comment]
mmmh still strange. Had to add an test for that

**Comment by hypery2k** [comment]
I added bundling for the app.

You can give `@toolisticon/ssl-hostinfo-prometheus-exporter@1.4.3-build1601704031` a try

**Comment by PLADASLO** [comment]
it doesn't work for me either
uname -a
Linux CH30L006 5.0.0-1027-azure #29~18.04.1-Ubuntu SMP Mon Nov 25 21:18:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

sudo ssl-hostinfo-prom
/usr/local/bin/ssl-hostinfo-prom: 1: /usr/local/bin/ssl-hostinfo-prom: Syntax error: "(" unexpected

**Comment by hypery2k** [comment]
you can give `@toolisticon/ssl-hostinfo-prometheus-exporter@1.4.4` a try
